global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:9100"]
        labels:
          app: "node"

  - job_name: "alertmanager"
    static_configs:
      - targets: ["localhost:9093"]
        labels:
          app: "alertmanager"

  - job_name: "ves-logcollector"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9000"]
        labels:
          app: "logcollector"
